export const books = [
  {
    id: 1,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    image: "https://picsum.photos/seed/1984/200/300",
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    image: "https://picsum.photos/seed/mockingbird/200/300",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    image: "https://picsum.photos/seed/gatsby/200/300",
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    image: "https://picsum.photos/seed/catcher/200/300",
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    image: "https://picsum.photos/seed/bravenewworld/200/300",
  },
  {
    id: 6,
    title: "Moby Dick",
    author: "Herman Melville",
    year: 1851,
    image: "https://picsum.photos/seed/mobydick/200/300",
  },
  {
    id: 7,
    title: "The Odyssey",
    author: "Homer",
    year: 800,
    image: "https://picsum.photos/seed/odyssey/200/300",
  },
  {
    id: 8,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    image: "https://picsum.photos/seed/prideandprejudice/200/300",
  },
  {
    id: 9,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    image: "https://picsum.photos/seed/hobbit/200/300",
  },
  {
    id: 10,
    title: "Animal Farm",
    author: "George Orwell",
    year: 1945,
    image: "https://picsum.photos/seed/animalfarm/200/300",
  },
  {
    id: 11,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    image: "https://picsum.photos/seed/warandpeace/200/300",
  },
  {
    id: 12,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    image: "https://picsum.photos/seed/crimeandpunishment/200/300",
  },
  {
    id: 13,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    image: "https://picsum.photos/seed/brotherskaramazov/200/300",
  },
  {
    id: 14,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    year: 1320,
    image: "https://picsum.photos/seed/divinecomedy/200/300",
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    image: "https://picsum.photos/seed/doriangray/200/300",
  },
  {
    id: 16,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    image: "https://picsum.photos/seed/lotr/200/300",
  },
  {
    id: 17,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    image: "https://picsum.photos/seed/catcher2/200/300",
  },
  {
    id: 18,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: 1953,
    image: "https://picsum.photos/seed/fahrenheit/200/300",
  },
  {
    id: 19,
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    year: 1969,
    image: "https://picsum.photos/seed/slaughterhouse/200/300",
  },
  {
    id: 20,
    title: "The Fault in Our Stars",
    author: "John Green",
    year: 2012,
    image: "https://picsum.photos/seed/faultinourstars/200/300",
  },
  {
    id: 21,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    year: 2008,
    image: "https://picsum.photos/seed/hungergames/200/300",
  },
  {
    id: 22,
    title: "The Giver",
    author: "Lois Lowry",
    year: 1993,
    image: "https://picsum.photos/seed/giver/200/300",
  },
  {
    id: 23,
    title: "Ready Player One",
    author: "Ernest Cline",
    year: 2011,
    image: "https://picsum.photos/seed/readyplayerone/200/300",
  },
  {
    id: 24,
    title: "Ender's Game",
    author: "Orson Scott Card",
    year: 1985,
    image: "https://picsum.photos/seed/endersgame/200/300",
  },
  {
    id: 25,
    title: "The Martian",
    author: "Andy Weir",
    year: 2011,
    image: "https://picsum.photos/seed/martian/200/300",
  },
  {
    id: 26,
    title: "Dune",
    author: "Frank Herbert",
    year: 1965,
    image: "https://picsum.photos/seed/dune/200/300",
  },
  {
    id: 27,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    year: 1996,
    image: "https://picsum.photos/seed/got/200/300",
  },
  {
    id: 28,
    title: "The Winds of Winter",
    author: "George R.R. Martin",
    year: 2022,
    image: "https://picsum.photos/seed/winter/200/300",
  },
  {
    id: 29,
    title: "Circe",
    author: "Madeline Miller",
    year: 2018,
    image: "https://picsum.photos/seed/circe/200/300",
  },
  {
    id: 30,
    title: "The Night Circus",
    author: "Erin Morgenstern",
    year: 2011,
    image: "https://picsum.photos/seed/nightcircus/200/300",
  },
];
